# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "molokai"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

# Enable autocomplete layer

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = 'colorscheme'

[[layers]]
name = "VersionControl"

[[layers]]
name = 'cscope'

[[layers]]
name = "autocomplete"
auto-completion-return-key-behavior = "smart"
auto-completion-tab-key-behavior = "smart"
auto-completion-delay = 200
auto-completion-complete-with-key-sequence = "nil"
auto-completion-complete-with-key-sequence-delay = 0.1

[[layers]]
name = "debug"

[[layers]]
name = "git"

[[layers]]
name = "lang#c"

[[layers]]
  name = "lang#markdown"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#sh"

[[layers]]
name = "lang#vim"
